### ISSUE TITLE
Streams3 adaptor / transform (s)

### ISSUE THREAD

**Issue by Fishrock123** [Fishrock123/bob#18]
Heya @mcollina & @mafintosh - I think this is the next required step here, since we'd need this kinda thing to be able to do anything in node core anyways.

I've created a repo for this at https://github.com/Fishrock123/bob-streams3 and invited you both as collaborators. It contains some basic bits but no functioning code.

There are a good bit of docs and examples lying around here & in the linked-to module repos, please holler if you need any of my help.

**Comment by Fishrock123** [comment]
Ok so I dunno why I didn't think about this before but pull-stream has modules that do this that I should be able to adapt. I am not sure they do it 100% correctly, but if it works it works.

e.g. https://github.com/pull-stream/pull-stream-to-stream, https://www.npmjs.com/package/pull-to-stream

**Comment by Fishrock123** [comment]
Some semi-working progress here: https://github.com/Fishrock123/bob/tree/streams3-adaptor

Seems to work(?): `fs-source -> duplex --pipe-> duplex -> fs-sink`

Doesn't work: `fs-source -> duplex --pipe-> zlib-gzip-transform --pipe-> duplex -> fs-sink`

cc @mcollina

**Comment by mcollina** [comment]
Have you got a repro for that? What can I run to test?

I would do a slightly different design on the Duplex. I would create an
internal bob sink/source, and wrap that in the duplex. I would not expose
bob specific methods, such as pull or next. I would also create two more
pairs on bindSink/bindSource and have an internal sink/source to match for
the counterpart. Something like:

source -> (sink -> duplex) -> zlib -> (duplex -> source) -> sink

I would also avoid listening for "finish" and "close", but rather rely on:

- _destroy
- autoDestroy option

Cheers

Matteo


Il giorno mer 12 giu 2019 alle ore 02:16 Jeremiah Senkpiel <
notifications@github.com> ha scritto:

**Comment by Fishrock123** [comment]
`source -> (sink -> duplex) -> zlib -> (duplex -> source) -> sink`

Wouldn't constructing that be really awkward?

Ideally I'd like:
```js
Stream(sourceOrStream).pipe(streams3_transform).pipe(Stream(sinkOrStream))
```

**Comment by Fishrock123** [comment]
OK I think it works. Like. Actually. WORKS.

https://github.com/Fishrock123/bob/blob/streams3-adaptor/helpers/bob-duplex.js

Test cases: 
_(manually verify the output file, `readme_` or `readme.gz` (there is an ungzip helper in `tests/`)._
_(may require Node 13)_
```
node tests/bob-streams3-from-source.js readme.md

node tests/bob-streams3-to-sink.js readme.md

node tests/bob-streams3-files.js readme.md

node tests/bob-streams3-zlib.js readme.md
```

Use `NODE_DEBUG=bob` to see what is happening.

Replace `readme.md` with your choice of file.

**Comment by Fishrock123** [comment]
Ok next bit is to write reasonable automated tests, haha 😬 .
