### ISSUE TITLE
Proposal: make `start()` standard instead of suggesting to automatically pull.

### ISSUE THREAD

**Issue by Fishrock123** [Fishrock123/bob#24]
I like being explicit in intent - I feel it would be better to not include default code examples that automatically start from sinks and rather just always include `start()`. (And no longer have start me an "extension")

**Comment by jasnell** [comment]
Definitely agree with this. The Sink should be in complete control over when to start data flow.

**Comment by Fishrock123** [comment]
To be clear - it already is, this is discussing making it less actually. I.e. making the outside code have to tell the sink to start explicitly.

**Comment by Fishrock123** [comment]
Something like

`Stream(source, transform, sink).start()` could then invoke `sink.start()`, or, more verbosely:

```
sink.bindSource(source, err => {}).start()
```

**Comment by Fishrock123** [comment]
Current extension reference: https://github.com/Fishrock123/bob/blob/master/reference-extension-start.js

**Comment by jasnell** [comment]
Heh, sorry, wasn't being clear. In the uses I have in mind, the sink would call start but it wouldn't start automatically after bind. We're saying the same things but with different code calling start sometime after the bind has been performed.

**Comment by Fishrock123** [comment]
If we make `start()` standard we can move the "bindCb" (the exit/error callback) to `start()` instead which would make `bindSource()` not have developer polymorphism. I think that would probably be a good idea. (or, have start return a promise) (or conditionally) (one or the other)
