### ISSUE TITLE
convert to npm module with 'top-level' require-able helpers

### ISSUE THREAD

**Issue by Fishrock123** [Fishrock123/bob#33]
e.g. `require('bob/status')`, `require('bob/verify')`, `require('bob/stream')`...

Would make maintaining the spec-ness of this repo much easier.

**Comment by Raynos** [comment]
:+1: If the end goal is to land this in node core then having all bob related work in a single repo might make it easier to work on.

**Comment by Fishrock123** [comment]
Past conversations indicated people wanted it as separate modules. I think parts like the fs source/sink and whatnot can be , but some should probably just live here.

**Comment by Fishrock123** [comment]
done now
